import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { DataTable } from '../components/DataTable';
import { FilterBar } from '../components/FilterBar';
import { Modal } from '../components/Modal';
import { PaginationBar } from '../components/PaginationBar';
import { clientsApi, ordersApi, productsApi } from '../lib/resources';
import { money, type Client, type Order, type OrderStatus, type Product } from '../lib/types';

type DraftItem = { productId: string; quantity: string; unitPrice: string };
const blankItem = (): DraftItem => ({ productId: '', quantity: '1', unitPrice: '' });
const labels: Record<OrderStatus, string> = { DRAFT: 'RASCUNHO', CONFIRMED: 'CONFIRMADO', CANCELLED: 'CANCELADO' };

/** Orders page with filters and a master-detail order editor. */
export function OrdersPage() {
  const [rows, setRows] = useState<Order[]>([]); const [clients, setClients] = useState<Pick<Client, 'id' | 'name' | 'active'>[]>([]); const [products, setProducts] = useState<Pick<Product, 'id' | 'sku' | 'name' | 'price' | 'active'>[]>([]);
  const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [search, setSearch] = useState(''); const [draftSearch, setDraftSearch] = useState(''); const [statusFilter, setStatusFilter] = useState<OrderStatus | ''>('');
  const [editing, setEditing] = useState<Order | null>(null); const [clientId, setClientId] = useState(''); const [status, setStatus] = useState<OrderStatus>('DRAFT'); const [notes, setNotes] = useState(''); const [items, setItems] = useState<DraftItem[]>([blankItem()]); const [open, setOpen] = useState(false); const [error, setError] = useState(''); const pageSize = 20;
  async function load(nextPage = page, nextSearch = search, nextStatus = statusFilter) { try { const result = await ordersApi.list({ page: nextPage, pageSize, search: nextSearch, status: nextStatus }); setRows(result.data); setTotal(result.total); setPage(result.page); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Erro ao carregar pedidos'); } }
  useEffect(() => { void Promise.all([load(), clientsApi.options(), productsApi.options()]).then(([, clientResult, productResult]) => { setClients(clientResult.data.filter((client) => client.active)); setProducts(productResult.data.filter((product) => product.active)); }); }, []);
  const preview = useMemo(() => items.reduce((sum, item) => sum + Number(item.quantity || 0) * Number(item.unitPrice || 0), 0), [items]);
  function create() { setEditing(null); setClientId(clients[0]?.id ?? ''); setStatus('DRAFT'); setNotes(''); setItems([blankItem()]); setError(''); setOpen(true); }
  function edit(row: Order) { setEditing(row); setClientId(row.clientId); setStatus(row.status); setNotes(row.notes ?? ''); setItems(row.items.map((item) => ({ productId: item.productId, quantity: String(item.quantity), unitPrice: String(item.unitPrice) }))); setError(''); setOpen(true); }
  function updateItem(index: number, patch: Partial<DraftItem>) { setItems((current) => current.map((item, itemIndex) => { if (itemIndex !== index) return item; const next = { ...item, ...patch }; if (patch.productId) next.unitPrice = String(products.find((product) => product.id === patch.productId)?.price ?? ''); return next; })); }
  async function save() { if (!clientId || items.some((item) => !item.productId || Number(item.quantity) <= 0 || Number(item.unitPrice) < 0)) { setError('Preencha cliente e itens válidos'); return; } const payload = { clientId, status, notes: notes || undefined, items: items.map((item) => ({ productId: item.productId, quantity: Number(item.quantity), unitPrice: Number(item.unitPrice) })) }; try { if (editing) await ordersApi.update(editing.id, payload); else await ordersApi.create(payload); setOpen(false); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Erro ao salvar pedido'); } }
  function filter(event: FormEvent) { event.preventDefault(); setSearch(draftSearch); void load(1, draftSearch, statusFilter); }
  return <section><h1 className="module-title">PEDIDOS</h1>
    <FilterBar onSubmit={filter} onClear={() => { setDraftSearch(''); setSearch(''); setStatusFilter(''); void load(1, '', ''); }} actions={<button type="button" className="btn btn-primary" onClick={create}>Novo</button>}><input placeholder="Número ou cliente" value={draftSearch} onChange={(event) => setDraftSearch(event.target.value)} /><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value as OrderStatus | '')}><option value="">Todos os status</option><option value="DRAFT">Rascunho</option><option value="CONFIRMED">Confirmado</option><option value="CANCELLED">Cancelado</option></select></FilterBar>
    {error ? <p className="form-error">{error}</p> : null}
    <DataTable rows={rows} rowKey={(row) => row.id} columns={[{ key: 'number', header: 'Número', render: (row) => row.number }, { key: 'client', header: 'Cliente', render: (row) => row.client.name }, { key: 'status', header: 'Status', render: (row) => <span className={`badge ${row.status === 'CONFIRMED' ? 'badge--success' : row.status === 'CANCELLED' ? 'badge--danger' : 'badge--warning'}`}>{labels[row.status]}</span> }, { key: 'total', header: 'Total', render: (row) => money(row.total) }, { key: 'actions', header: 'Ações', render: (row) => <div className="row-actions"><button className="btn btn-ghost" onClick={() => edit(row)}>Editar</button>{row.status !== 'CANCELLED' ? <button className="btn btn-ghost" onClick={() => void ordersApi.remove(row.id).then(() => load())}>Cancelar</button> : null}</div> }]} />
    <PaginationBar page={page} pageSize={pageSize} total={total} onChange={(next) => void load(next)} />
    <Modal open={open} title={editing ? `Editar ${editing.number}` : 'Novo pedido'} onClose={() => setOpen(false)} footer={<><button className="btn btn-outline" onClick={() => setOpen(false)}>Cancelar</button><button className="btn btn-primary" onClick={() => void save()}>Salvar</button></>}><div className="form-field"><label>Cliente *</label><select value={clientId} onChange={(event) => setClientId(event.target.value)}><option value="">Selecione</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></div><div className="form-field"><label>Status *</label><select value={status} onChange={(event) => setStatus(event.target.value as OrderStatus)}><option value="DRAFT">Rascunho</option><option value="CONFIRMED">Confirmado</option><option value="CANCELLED">Cancelado</option></select></div><div className="form-field"><label>Observações</label><textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></div><div className="items-editor">{items.map((item, index) => <div className="items-editor__row" key={index}><select value={item.productId} onChange={(event) => updateItem(index, { productId: event.target.value })}><option value="">Produto</option>{products.map((product) => <option key={product.id} value={product.id}>{product.sku} — {product.name}</option>)}</select><input type="number" min="0.001" step="0.001" value={item.quantity} onChange={(event) => updateItem(index, { quantity: event.target.value })} /><input type="number" min="0" step="0.01" value={item.unitPrice} onChange={(event) => updateItem(index, { unitPrice: event.target.value })} /><button className="btn btn-ghost" disabled={items.length === 1} onClick={() => setItems((current) => current.filter((_, itemIndex) => itemIndex !== index))}>Remover</button></div>)}<button className="btn btn-outline" onClick={() => setItems((current) => [...current, blankItem()])}>Adicionar item</button><strong>Total: {money(preview)}</strong></div></Modal>
  </section>;
}
